<a href="https://colab.research.google.com/github/3B032013/2025_ML_hws/blob/main/hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業1 - (第四週)

## *題組1 模擬多隱藏層的全連接神經網路(DNN)

## 1-1 各激活函數定義(Sigmoid、ReLU、Softmax)

In [8]:
import numpy as np
# Sigmoid激發函數
def sigmoid(x):
  return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
  return np.maximum(0, x)

# Softmax激發函數
def softmax(x):
  c=np.max(x)
  x = x - c
  return np.exp(x) / np.sum(np.exp(x))

## 1-2 輸入層設定6個神經元

In [9]:
# 設定6個隨機原始資料 放入x中
x=np.array([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])

## 1-3 第一隱藏層有5個神經元 激發函數使用ReLU

In [10]:
W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
 [0.2, 0.3, 0.4, 0.5, 0.6],
 [0.3, 0.4, 0.5, 0.6, 0.7],
 [0.4, 0.5, 0.6, 0.7, 0.8],
 [0.5, 0.6, 0.7, 0.8, 0.9],
 [0.6, 0.7, 0.8, 0.9, 1.0]])
b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [11]:
z1 = np.dot(x, W1) + b1
h1 = relu(z1)
print(h1)

[2.3 2.4 2.5 2.6 2.7]


## 1-4 第二隱藏層有4個神經元 激發函數使用ReLU

In [12]:
W2=np.array([[0.2, 0.3, 0.4, 0.5],
 [0.3, 0.4, 0.5, 0.6],
 [0.4, 0.5, 0.6, 0.7],
 [0.5, 0.6, 0.7, 0.8],
 [0.6, 0.7, 0.8, 0.9]])
b2=np.array([0.1, 0.2, 0.3, 0.4])

In [13]:
z2 = np.dot(h1, W2) + b2
h2 = relu(z2)
print(h2)

[5.2  6.55 7.9  9.25]


## 1-5 第三隱藏層有4個神經元 激發函數使用sigmoid

In [14]:
W3=np.array([[0.3, 0.4, 0.5, 0.6],
 [0.4, 0.5, 0.6, 0.7],
 [0.5, 0.6, 0.7, 0.8],
 [0.6, 0.7, 0.8, 0.9]])
b3=np.array([0.1, 0.2, 0.3, 0.4])

In [15]:
z3 = np.dot(h2, W3) + b3
h3 = sigmoid(z3)
print(h3)

[0.99999896 0.99999995 1.         1.        ]


## 1-6 輸出層需有3個神經元 激發函數使用softmax

In [16]:
W4=np.array([[0.4, 0.5, 0.6],
 [0.5, 0.6, 0.7],
 [0.6, 0.7, 0.8],
 [0.7, 0.8, 0.9]])
b4=np.array([0.1, 0.2, 0.3])

In [17]:
z4 = np.dot(h3, W4) + b4
y_hat = softmax(z4)
# y_hat為最終計算的各項機率結果
print(y_hat)

[0.18632375 0.3071959  0.50648035]


## 1-7 使用cross_entropy_error衡量y_hat與y之間的誤差值

In [18]:
def cross_entropy_error(y_hat, y):
  return -np.sum(y * np.log(y_hat + 1e-7))

In [19]:
# 假設第三種為真實結果
y=[0, 0, 1]

In [20]:
np.log(y_hat + 1e-7)

array([-1.68026899, -1.18026931, -0.68026955])

In [21]:
y*np.log(y_hat + 1e-7)

array([-0.        , -0.        , -0.68026955])

In [22]:
-np.sum(y * np.log(y_hat + 1e-7))

0.6802695473719652

In [23]:
cross_entropy_error(y_hat, y)

0.6802695473719652

## *題組2 設計dnn函數 搭配gradio套件

In [24]:
!pip install gradio

In [34]:
import numpy as np
import gradio as gr
def dnn(x):
  # 第一隱藏層
  W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
    [0.2, 0.3, 0.4, 0.5, 0.6],
    [0.3, 0.4, 0.5, 0.6, 0.7],
    [0.4, 0.5, 0.6, 0.7, 0.8],
    [0.5, 0.6, 0.7, 0.8, 0.9],
    [0.6, 0.7, 0.8, 0.9, 1.0]])
  b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])
  z1 = np.dot(x, W1) + b1
  h1 = relu(z1)

  # 第二隱藏層
  W2=np.array([[0.2, 0.3, 0.4, 0.5],
    [0.3, 0.4, 0.5, 0.6],
    [0.4, 0.5, 0.6, 0.7],
    [0.5, 0.6, 0.7, 0.8],
    [0.6, 0.7, 0.8, 0.9]])
  b2=np.array([0.1, 0.2, 0.3, 0.4])
  z2 = np.dot(h1, W2) + b2
  h2 = relu(z2)

  # 第三隱藏層
  W3=np.array([[0.3, 0.4, 0.5, 0.6],
    [0.4, 0.5, 0.6, 0.7],
    [0.5, 0.6, 0.7, 0.8],
    [0.6, 0.7, 0.8, 0.9]])
  b3=np.array([0.1, 0.2, 0.3, 0.4])
  z3 = np.dot(h2, W3) + b3
  h3 = sigmoid(z3)

  # 輸出層
  W4=np.array([[0.4, 0.5, 0.6],
    [0.5, 0.6, 0.7],
    [0.6, 0.7, 0.8],
    [0.7, 0.8, 0.9]])
  b4=np.array([0.1, 0.2, 0.3])
  z4 = np.dot(h3, W4) + b4
  y_hat = softmax(z4)
  # y_hat為最終計算的各項機率結果
  return y_hat

In [35]:
x=np.array([-3.0, -2.0, -1.0, 1.0, 2.0, 3.0])
y_hat = dnn(x)
# 最終結果與前提一致
print(y_hat)

[0.18632375 0.3071959  0.50648035]


In [38]:
# 建立 Gradio 介面
def classify_input(x1, x2, x3, x4, x5, x6):
  x = np.array([x1, x2, x3, x4, x5, x6]).reshape(1, 6)  # 保證為1*6形狀
  y_hat = dnn(x)
  # 回傳機率最高之值(1、2、3)
  return np.argmax(y_hat) + 1

interface = gr.Interface(fn=classify_input,inputs=[gr.Number(label=f"Feature {i}") for i in range(1, 7)], outputs="text", title="DNN Classifier", description="輸入6個特徵值，模型將輸出機率最高的類別 (1, 2, 3)")

# 啟動介面
interface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://00f9cb83972ae776d7.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
