<a href="https://colab.research.google.com/github/3B032013/2025_ML_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業2 - (第四週)

## *題組1 多隱藏層的全連接神經網路 "批次學習"

## 1-1 各激發函數定義(Sigmoid、ReLU、Softmax)

In [1]:
import numpy as np
# Sigmoid激發函數
def sigmoid(x):
  return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
  return np.maximum(0, x)

# Softmax激發函數
def softmax(x):
  x = x - np.max(x, axis=-1, keepdims=True)
  return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

## 1-2 輸入層設定批次輸入5筆資料 每筆6個神經元

In [2]:
# 批次輸入5筆資料
batch_size=5

# 每筆6個神經元 所以共5*6=30
X=np.array([[10.0, 8.0, 11.0, 4.0, 3.0, 0.0],
    [-16.0, 4.0, -10.0, 8.0, 10.0, 12.0],
    [1.0, 3.0, -9.0, 7.0, 9.0, 11.0],
    [8.0, 6.0, 4.0, -4.0, 4.0, -6.0],
    [2.0, -3.0, 4.0, 5.0, -6.0, 7.0]])

# 真實結果
Y=np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]])

## 1-3 第一隱藏層有5個神經元 激發函數使用ReLU

In [3]:
W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
 [0.2, 0.3, 0.4, 0.5, 0.6],
 [0.3, 0.4, 0.5, 0.6, 0.7],
 [0.4, 0.5, 0.6, 0.7, 0.8],
 [0.5, 0.6, 0.7, 0.8, 0.9],
 [0.6, 0.7, 0.8, 0.9, 1.0]])
b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [4]:
z1 = np.dot(X, W1) + b1
h1 = relu(z1)
print(h1)

[[ 9.1 12.8 16.5 20.2 23.9]
 [11.7 12.6 13.5 14.4 15.3]
 [12.  14.3 16.6 18.9 21.2]
 [ 0.1  1.4  2.7  4.   5.3]
 [ 4.1  5.1  6.1  7.1  8.1]]


## 1-4 第二隱藏層有4個神經元 激發函數使用ReLU

In [5]:
W2=np.array([[0.2, 0.3, 0.4, 0.5],
 [0.3, 0.4, 0.5, 0.6],
 [0.4, 0.5, 0.6, 0.7],
 [0.5, 0.6, 0.7, 0.8],
 [0.6, 0.7, 0.8, 0.9]])
b2=np.array([0.1, 0.2, 0.3, 0.4])

In [6]:
z2 = np.dot(h1, W2) + b2
h2 = relu(z2)
print(h2)

[[36.8  45.15 53.5  61.85]
 [28.   34.85 41.7  48.55]
 [35.6  44.   52.4  60.8 ]
 [ 6.8   8.25  9.7  11.15]
 [13.3  16.45 19.6  22.75]]


## 1-5 第三隱藏層有4個神經元 激發函數使用Sigmoid

In [7]:
W3=np.array([[-0.3, 0.4, -0.5, 0.6],
 [-0.4, 0.5, -0.6, 0.7],
 [-0.5, -0.6, 0.7, 0.8],
 [0.6, -0.7, 0.8, -0.9]])
b3=np.array([0.1, 0.2, 0.3, 0.4])

In [8]:
z3 = np.dot(h2, W3) + b3
h3 = sigmoid(z3)
print(h3)

[[8.03065287e-09 3.46927827e-17 1.00000000e+00 1.00000000e+00]
 [8.65463301e-07 7.81614372e-14 1.00000000e+00 1.00000000e+00]
 [1.68317304e-08 4.87415415e-17 1.00000000e+00 1.00000000e+00]
 [3.22954647e-02 1.38592584e-03 9.99528915e-01 9.99657878e-01]
 [1.33165528e-03 8.82946804e-07 9.99999848e-01 9.99999723e-01]]


## 1-6 輸出層需有3個神經元 激發函數使用Softmax

In [9]:
W4=np.array([[0.4, 0.5, 0.6],
 [-0.1, 0.6, -0.7],
 [-0.6, 0.9, -0.8],
 [0.7, -0.3, 0.9]])
b4=np.array([0.2, 0.2, 0.3])

In [16]:
z4 = np.dot(h3, W4) + b4
y_hat = softmax(z4)
# y_hat為最終計算的各項機率結果
print(y_hat)

[[0.3        0.8        0.4       ]
 [0.30000035 0.80000043 0.40000052]
 [0.30000001 0.80000001 0.40000001]
 [0.31282276 0.81665795 0.41847609]
 [0.30053247 0.8006663  0.40079825]]
[[0.26639018 0.43920315 0.29440668]
 [0.26639015 0.43920315 0.2944067 ]
 [0.26639018 0.43920315 0.29440668]
 [0.26549896 0.4394158  0.29508524]
 [0.26635367 0.43920174 0.29444458]]


## 1-7 使用cross_entropy_error衡量y_hat與y之間的誤差值

In [11]:
def cross_entropy_error(y, t):
  if y.ndim == 1:
    t = t.reshape(1, t.size)
    y = y.reshape(1, y.size)

  batch_size = y.shape[0]
  return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [12]:
np.log(y_hat + 1e-7)

array([[-1.32279284, -0.82279299, -1.22279288],
       [-1.32279293, -0.82279299, -1.22279279],
       [-1.32279285, -0.82279299, -1.22279288],
       [-1.32614397, -0.82230893, -1.22049068],
       [-1.32292987, -0.82279619, -1.22266413]])

In [13]:
Y*np.log(y_hat + 1e-7)

array([[-0.        , -0.        , -1.22279288],
       [-1.32279293, -0.        , -0.        ],
       [-0.        , -0.82279299, -0.        ],
       [-0.        , -0.        , -1.22049068],
       [-1.32292987, -0.        , -0.        ]])

In [14]:
-np.sum(Y * np.log(y_hat + 1e-7))

np.float64(5.9117993571691425)

In [15]:
cross_entropy_error(y_hat, Y)

np.float64(1.1823598714338286)