<a href="https://colab.research.google.com/github/3B032013/2025_ML_hws/blob/main/hw2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業2 - (第四週)

## *題組1 多隱藏層的全連接神經網路 "批次學習"

## 1-1 各激發函數定義(Sigmoid、ReLU、Softmax)

In [73]:
import numpy as np
# Sigmoid激發函數
def sigmoid(x):
  return 1/(1+np.exp(-x))

# ReLU激發函數
def relu(x):
  return np.maximum(0, x)

# Softmax激發函數
def softmax(x):
  c=np.max(x)
  x = x - c
  return np.exp(x) / np.sum(np.exp(x))

## 1-2 輸入層設定批次輸入5筆資料 每筆6個神經元

In [74]:
# 批次輸入5筆資料
batch_size=5

# 每筆6個神經元 所以共5*6=30
X=np.array([[10.0, 8.0, -6.0, 4.0, -2.0, 0.0],
    [-16.0, 4.0, -10.0, 8.0, 10.0, 12.0],
    [1.0, 3.0, -9.0, 7.0, 9.0, 11.0],
    [8.0, 6.0, 4.0, -4.0, 4.0, -6.0],
    [2.0, -3.0, 4.0, 5.0, -6.0, 7.0]])

# 真實結果
Y=np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]])

## 1-3 第一隱藏層有5個神經元 激發函數使用ReLU

In [75]:
W1=np.array([[0.1, 0.2, 0.3, 0.4, 0.5],
 [0.2, 0.3, 0.4, 0.5, 0.6],
 [0.3, 0.4, 0.5, 0.6, 0.7],
 [0.4, 0.5, 0.6, 0.7, 0.8],
 [0.5, 0.6, 0.7, 0.8, 0.9],
 [0.6, 0.7, 0.8, 0.9, 1.0]])
b1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [76]:
z1 = np.dot(X, W1) + b1
h1 = relu(z1)
print(h1)

[[ 1.5  3.   4.5  6.   7.5]
 [11.7 12.6 13.5 14.4 15.3]
 [12.  14.3 16.6 18.9 21.2]
 [ 0.1  1.4  2.7  4.   5.3]
 [ 4.1  5.1  6.1  7.1  8.1]]


## 1-4 第二隱藏層有4個神經元 激發函數使用ReLU

In [77]:
W2=np.array([[0.2, 0.3, 0.4, 0.5],
 [0.3, 0.4, 0.5, 0.6],
 [0.4, 0.5, 0.6, 0.7],
 [0.5, 0.6, 0.7, 0.8],
 [0.6, 0.7, 0.8, 0.9]])
b2=np.array([0.1, 0.2, 0.3, 0.4])

In [78]:
z2 = np.dot(h1, W2) + b2
h2 = relu(z2)
print(h2)

[[10.6  12.95 15.3  17.65]
 [28.   34.85 41.7  48.55]
 [35.6  44.   52.4  60.8 ]
 [ 6.8   8.25  9.7  11.15]
 [13.3  16.45 19.6  22.75]]


## 1-5 第三隱藏層有4個神經元 激發函數使用Sigmoid

In [79]:
W3=np.array([[0.3, 0.4, 0.5, 0.6],
 [0.4, 0.5, 0.6, 0.7],
 [0.5, 0.6, 0.7, 0.8],
 [0.6, 0.7, 0.8, 0.9]])
b3=np.array([0.1, 0.2, 0.3, 0.4])

In [80]:
z3 = np.dot(h2, W3) + b3
h3 = sigmoid(z3)
print(h3)

[[1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [1.         1.         1.         1.        ]
 [0.99999996 1.         1.         1.        ]
 [1.         1.         1.         1.        ]]


## 1-6 輸出層需有3個神經元 激發函數使用Softmax

In [81]:
W4=np.array([[0.4, 0.5, 0.6],
 [0.5, 0.6, 0.7],
 [0.6, 0.7, 0.8],
 [0.7, 0.8, 0.9]])
b4=np.array([0.1, 0.2, 0.3])

In [82]:
z4 = np.dot(h3, W4) + b4
y_hat = softmax(z4)
# y_hat為最終計算的各項機率結果
print(y_hat)

[[0.03726474 0.06143918 0.10129608]
 [0.03726474 0.06143918 0.10129608]
 [0.03726474 0.06143918 0.10129608]
 [0.03726474 0.06143918 0.10129608]
 [0.03726474 0.06143918 0.10129608]]


## 1-7 使用cross_entropy_error衡量y_hat與y之間的誤差值

In [83]:
def cross_entropy_error(y_hat, y):
  return -np.sum(y * np.log(y_hat + 1e-7))

In [84]:
np.log(y_hat + 1e-7)

array([[-3.28970489, -2.78970595, -2.28970659],
       [-3.28970489, -2.78970595, -2.28970659],
       [-3.28970489, -2.78970595, -2.28970659],
       [-3.28970491, -2.78970597, -2.28970662],
       [-3.28970489, -2.78970595, -2.28970659]])

In [85]:
Y*np.log(y_hat + 1e-7)

array([[-0.        , -0.        , -2.28970659],
       [-3.28970489, -0.        , -0.        ],
       [-0.        , -2.78970595, -0.        ],
       [-0.        , -0.        , -2.28970662],
       [-3.28970489, -0.        , -0.        ]])

In [86]:
-np.sum(Y * np.log(y_hat + 1e-7))

np.float64(13.948528949294603)

In [87]:
cross_entropy_error(y_hat, Y)

np.float64(13.948528949294603)