<a href="https://colab.research.google.com/github/3B032013/2025_DL_hws/blob/main/hw6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業6-2

In [22]:
import numpy as np

## 一、自訂三個輸入單字x1、x2、x3 及初始隱藏狀態0

In [23]:
# 自訂輸入向量 x1, x2, x3
x1 = np.array([0.1, 0.2, 0.3])
x2 = np.array([0.5, 0.4, 0.3])
x3 = np.array([0.0, 0.1, 0.0])

# 初始隱藏狀態 h0
h0 = np.zeros(4)

## 二、自訂RNN神經元權重 Wx 、 Wh 、b

In [24]:
# 自訂 RNN 權重
Wx = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])  # shape: (3, 4)

Wh = np.array([
    [0.1, 0.0, 0.1, 0.0],
    [0.0, 0.1, 0.0, 0.1],
    [0.1, 0.1, 0.1, 0.1],
    [0.2, 0.2, 0.2, 0.2]
])  # shape: (4, 4)

b = np.array([0.1, 0.2, 0.3, 0.4])  # shape: (4,)

## 三、RNN激活函數使用tanh

In [25]:
# tanh 函數
def tanh(x):
    return np.tanh(x)

## 四、計算h1

In [26]:
# h1 = tanh(x1 @ Wx + h0 @ Wh + b)
h1 = tanh(np.dot(x1, Wx) + np.dot(h0, Wh) + b)
print("h1 =", h1)

h1 = [0.44624361 0.56489955 0.66403677 0.74427687]


## 五、計算h2

In [27]:
# h2 = tanh(x2 @ Wx + h1 @ Wh + b)
h2 = tanh(np.dot(x2, Wx) + np.dot(h1, Wh) + b)
print("h2 =", h2)

h2 = [0.70636091 0.80467977 0.86675493 0.91407361]


## 六、計算h3

In [28]:
# h3 = tanh(x3 @ Wx + h2 @ Wh + b)
h3 = tanh(np.dot(x3, Wx) + np.dot(h2, Wh) + b)
print("h3 =", h3)

h3 = [0.45431667 0.54409767 0.61075603 0.68045356]


# 作業6-3

## 一、Decoder t=3 時的 query 向量 S3

In [29]:
S3 = np.array([2, 5, 3, 1])

## 二、計算注意力強度

In [30]:
e1 = np.dot(S3, h1)
e2 = np.dot(S3, h2)
e3 = np.dot(S3, h3)

e = np.array([e1, e2, e3])
print("注意力強度 e =", e)

注意力強度 e = [6.45337216 8.95045906 6.14184333]


In [31]:
def softmax_0(x): # x是一個向量
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

def softmax(x): # x 可以是一個向量或矩陣(多個向量)
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

a = softmax(e)  # [a1, a2, a3]
print("注意力權重 a =", a)

注意力權重 a = [0.07204931 0.87518707 0.05276362]


## 三、計算Decoder在t=3時所使用的c3

In [32]:
c3 = a[0] * h1 + a[1] * h2 + a[2] * h3
print("c3 =", c3)

c3 = [0.67432087 0.77365451 0.8386418  0.88951323]


In [33]:
#　或是以下
# h = np.array([h1, h2, h3])
# c3 = np.dot(a, h)
# c3

# 作業6-4

## 一、設定x1、x2、x3 及WQ、WK、WV向量

In [34]:
x1 = np.array([0.1, 0.2, 0.3])
x2 = np.array([0.5, 0.4, 0.3])
x3 = np.array([0.0, 0.1, 0.0])
X = np.array([x1, x2, x3])

In [35]:
WQ = np.array([
    [0, 0, 1],
    [1, 0, 0],
    [0, 0, 1]
])

WK = np.array([
    [1, 0, 1],
    [0, 1, 1],
    [0, 1, 0]
])

WV = np.array([
    [0, 2, 1],
    [1, 0, 3],
    [1, 0, 1]
])

## 二、計算出Q,K,V及 根號dk

In [36]:
Q = np.dot(X, WQ)
K = np.dot(X, WK)
V = np.dot(X, WV)

dk = K.shape[1]
sqrt_dk = np.sqrt(dk)

print("Q =\n", Q)
print("K =\n", K)
print("V =\n", V)
print("sqrt(dk) =", sqrt_dk)

Q =
 [[0.2 0.  0.4]
 [0.4 0.  0.8]
 [0.1 0.  0. ]]
K =
 [[0.1 0.5 0.3]
 [0.5 0.7 0.9]
 [0.  0.1 0.1]]
V =
 [[0.5 0.2 1. ]
 [0.7 1.  2. ]
 [0.1 0.  0.3]]
sqrt(dk) = 1.7320508075688772


## 三、利用Attention(Q,K,V)公式 計算x1、x2、x3的self-attention

In [37]:
def softmax(x): # x 可以是一個向量或矩陣(多個向量)
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

In [38]:
def Attention (Q, K, V):
  d = 3
  return np.dot(softmax(np.dot(Q, K.T) / np.sqrt(d)), V)

In [39]:
attention = Attention(Q, K, V)
attention

array([[0.45647162, 0.44582152, 1.17229779],
       [0.47993522, 0.4934196 , 1.24666349],
       [0.43603383, 0.40540839, 1.10849414]])

## 四、驗證q1、k1、v1是否與Q、K、V一致

In [40]:
# 單獨算
q1 = np.dot(x1, WQ)
k1 = np.dot(x1, WK)
v1 = np.dot(x1, WV)

print("q1 =", q1)
print("k1 =", k1)
print("v1 =", v1)

# 驗證是否等於 Q[0], K[0], V[0]
print("Q[0] =", Q[0])
print("K[0] =", K[0])
print("V[0] =", V[0])

q1 = [0.2 0.  0.4]
k1 = [0.1 0.5 0.3]
v1 = [0.5 0.2 1. ]
Q[0] = [0.2 0.  0.4]
K[0] = [0.1 0.5 0.3]
V[0] = [0.5 0.2 1. ]
